### ISSUE TITLE
iPhone SE Size?

### ISSUE THREAD

**Issue by thelefty** [sonburn/artboard-framer#1]
can we get support for the iPhone SE? That'd be epic. Thanks!

**Comment by sonburn** [comment]
@thelefty Version 0.4 which I just published added some tablet devices and iPhone SE, and improved device selection & information in plugin dialog. Hope that's what you are looking for!

**Comment by thelefty** [comment]
Dope! You're a stud. Thanks. One other idea I had was that it wouldn't need to be an artboard. If I have an png/jpg of a screen it would be sweet to just run a shortcut to frame that sucka.

**Comment by sonburn** [comment]
@thelefty The devices are stored in a library which has been added to your Sketch, so you should be able to insert a symbol instance the same way you would from another library or symbols page.
