### ISSUE TITLE
artboard-framer

### ISSUE THREAD

**Issue by csabaszamosy** [sonburn/artboard-framer#5]
does not work

**Comment by sonburn** [comment]
@csabaszamosy, could you please be more specific? What version of Mac, what version of Sketch? Has it ever worked for you?

**Comment by csabaszamosy** [comment]
Jason,
Hiya - hope all is well with you…
It worked before - not sure what version of sketch (48?)…
I am on Mac 10.11.6 / Sketch 48.2 / Artboard Framer 0.10…
When trying to run it, Just keeps saying “Artboard Framer library installed”…
Hope this helps?…
Csaba



Senior Product Design Lead
CX, UX, IxD, UI and Prototyping
Mobile: +44.7933.322763
					 

On 5 October 2018 at 23:06:05, Jason Burns (notifications@github.com) wrote:

@csabaszamosy, could you please be more specific? What version of Mac, what version of Sketch? Has it ever worked for you?
